title: Political Science Polarization
description: Studying of polarization through different social medias across various events
sitename: Complex Data Lab
baseurl: ""
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
